POST http://localhost:3000/category
Content-Type: application/json

{
    "name": "Food",
    "icon": "nutrition-outline"
}

######

GET http://localhost:3000/category

###

DELETE http://localhost:3000/category/55555555-5555-5555-5555-555555555555

