### Crear transacción INCOME (ingreso)
POST http://localhost:3000/transaction
Content-Type: application/json

{
  "walletId": "6fc835fb-dc23-41a1-877e-bb781ac3d08c",
  "categoryId": "40beecab-9892-4253-87f1-ccc133d68132",
  "type": "INCOME",
  "name": "Salario septiembre",
  "amount": 200000,
  "date": "2025-09-12T15:00:00.000Z"
}

### Crear transacción EXPENSE (gasto)
POST http://localhost:3000/transaction
Content-Type: application/json

{
  "walletId": "0bb0f7ea-1403-4abd-905c-bee142a289a6",
  "categoryId": "80c7685e-e80e-40db-b2b4-6b5875dc1abf",
  "type": "EXPENSE",
  "name": "COMPRÉ COMIDA",
  "amount": 5500,
  "date": "2025-09-12T16:00:00.000Z"
}

### Crear transacción INTEREST (ejemplo)
POST http://localhost:3000/transaction
Content-Type: application/json

{
  "walletId": "a258e515-e6df-4d55-a7a8-178d40d37d52",
  "type": "INTEREST",
  "name": "Interés cuenta ahorro",
  "amount": 50,
  "date": "2025-09-12T20:00:00.000Z"
}

### Crear transacción TRANSFER (movimiento entre cuentas)
POST http://localhost:3000/transaction
Content-Type: application/json

{
  "fromWalletId": "6fc835fb-dc23-41a1-877e-bb781ac3d08c",
  "toWalletId": "0bb0f7ea-1403-4abd-905c-bee142a289a6",
  "type": "TRANSFER",
  "name": "Movimiento entre cuentas",
  "amount": 7000,
  "date": "2025-09-12T18:30:00.000Z",
  "categoryId": "40beecab-9892-4253-87f1-ccc133d68132"
}

### Listar transacciones por wallet (ej: cuenta principal)
GET http://localhost:3000/transaction?limit=30

### Actualizar transacción (ej: cambiar fecha o nombre)
PATCH http://localhost:3000/transaction/REEMPLAZAR_POR_TRANSACTION_ID
Content-Type: application/json

{
  "date": "2025-09-15T12:00:00.000Z",
  "name": "Compra supermercado ajustada"
}

### Eliminar transacción
DELETE http://localhost:3000/transaction/839ca3fd-433c-44a4-bad0-f9dcf74fcc94
