### Crear wallet con balance inicial
POST http://localhost:3000/wallet
Content-Type: application/json

{
  "userId": "8537c041-04d9-4a28-9e6f-5a299b18e61d",
  "name": "Banco Ahorros",
  "type": "WALLET",
  "balance": 5000,
  "interestRate": 5.0
}

### Crear wallet sin balance (queda en 0 por default)
POST http://localhost:3000/wallet
Content-Type: application/json

{
  "userId": "8537c041-04d9-4a28-9e6f-5a299b18e61d",
  "name": "Tarjeta Crédito",
  "type": "CREDIT_CARD"
}

### Listar wallets por usuario
GET http://localhost:3000/wallet?userId=8537c041-04d9-4a28-9e6f-5a299b18e61d

### Eliminar wallet (cambia el id según lo que devuelva el POST)
DELETE http://localhost:3000/wallet/a258e515-e6df-4d55-a7a8-178d40d37d52
